#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
paperless_name = data.get("paperless_name","paperless-ngx")
random_key = secrets.token_hex(16)
PAPERLESS_SECRET_KEY = data.get("PAPERLESS_SECRET_KEY",random_key)
PAPERLESS_ADMIN_USER = data.get("PAPERLESS_ADMIN_USER","paperlessadmin")
PAPERLESS_ADMIN_PASSWORD = data.get("PAPERLESS_ADMIN_PASSWORD","P@perle5$")
PAPERLESS_ADMIN_MAIL = data.get("PAPERLESS_ADMIN_MAIL","")
PAPERLESS_TIME_ZONE = data.get("PAPERLESS_TIME_ZONE","America/Los_Angeles")
PAPERLESS_OCR_LANGUAGE = data.get("PAPERLESS_OCR_LANGUAGE","eng")
PAPERLESS_COOKIE_PREFIX = data.get("PAPERLESS_COOKIE_PREFIX","paperlessngx")

# PAperless CSRF settings
PAPERLESS_URL = data.get("PAPERLESS_URL","")

# tika and Gotenberg settings
PAPERLESS_TIKA_ENABLED = data.get("PAPERLESS_TIKA_ENABLED","1")
PAPERLESS_TIKA_GOTENBERG_ENDPOINT = data.get("gotenberg","http://127.0.0.1:3000")
PAPERLESS_TIKA_ENDPOINT = data.get("tika","http://127.0.0.1:9998")

# Db Config

POSTGRES_DB = data.get("POSTGRES_DB","paperless")
POSTGRES_USER = data.get("POSTGRES_USER","paperless")
POSTGRES_PASSWORD = data.get("POSTGRES_PASSWORD","p@perle$$")

db_config = {
    
    "POSTGRES_ROOT_HOST": "localhost",
    "POSTGRES_DATABASE": POSTGRES_DB,
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    
}
agent.write_envfile('database.env', db_config)

# Talk with agent using file descriptor.

# Setup configuration from user input.
agent.set_env("PAPERLESS_NGX_NAME", paperless_name)
agent.set_env("PAPERLESS_SECRET_KEY", PAPERLESS_SECRET_KEY)
agent.set_env("PAPERLESS_TIME_ZONE", PAPERLESS_TIME_ZONE)
agent.set_env("PAPERLESS_OCR_LANGUAGE", PAPERLESS_OCR_LANGUAGE)
agent.set_env("PAPERLESS_COOKIE_PREFIX", PAPERLESS_COOKIE_PREFIX)
agent.set_env("PAPERLESS_ADMIN_USER", PAPERLESS_ADMIN_USER)
agent.set_env("PAPERLESS_ADMIN_PASSWORD", PAPERLESS_ADMIN_PASSWORD)
agent.set_env("PAPERLESS_ADMIN_MAIL", PAPERLESS_ADMIN_MAIL)

#paperless CSRF settings
agent.set_env("PAPERLESS_URL", PAPERLESS_URL)

# Setup tika and gotenberg configuration from user input.
agent.set_env("PAPERLESS_TIKA_ENABLED", PAPERLESS_TIKA_ENABLED)
agent.set_env("gotenberg", PAPERLESS_TIKA_GOTENBERG_ENDPOINT)
agent.set_env("tika", PAPERLESS_TIKA_ENDPOINT)

# Setup PHP with safe defaults
agent.set_env("PHP_ENABLE_OPCACHE", "1")
agent.set_env("PHP_MEMORY_LIMIT", "512M")
# Configure Traefik to route "/paperlessngx" path requests to the paperlessngx service


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
