#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(16)
ADMIN_TOKEN = data.get("ADMIN_TOKEN","$argon2id$v=19$m=65540,t=3,p=4$NE9wcGMvYjB4bTNlRTJ0cGh3S2RYNlF0MngrVGE0bk1MWmJKMEJmeVlFRT0$fq3A5jFTYM4u16+LJkuSQdN0123y7rVfbJ4+cDwG/9I")

# Talk with agent using file descriptor.

agent.set_env("ADMIN_TOKEN", ADMIN_TOKEN)


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
