#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

config = {}

# Read current configuration from Redis
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["paperless_name"] = os.getenv("PAPERLESS_NGX_NAME","")
config["PAPERLESS_SECRET_KEY"] = os.getenv("PAPERLESS_SECRET_KEY","")
config["PAPERLESS_TIME_ZONE"] = os.getenv("PAPERLESS_TIME_ZONE","")
config["PAPERLESS_OCR_LANGUAGE"] = os.getenv("PAPERLESS_OCR_LANGUAGE","")
config["POSTGRES_DB"] = os.getenv("POSTGRES_DB","")
config["POSTGRES_USER"] = os.getenv("POSTGRES_USER","")
config["POSTGRES_PASSWORD"] = os.getenv("POSTGRES_PASSWORD","")
config["PAPERLESS_TIKA_ENABLED"] = os.getenv("PAPERLESS_TIKA_ENABLED","1")
config["gotenberg"] = os.getenv("PAPERLESS_TIKA_GOTENBERG_ENDPOINT","")
config["tika"] = os.getenv("PAPERLESS_TIKA_ENDPOINT","")
config["PAPERLESS_ADMIN_USER"] = os.getenv("PAPERLESS_ADMIN_USER","")
config["PAPERLESS_ADMIN_PASSWORD"] = os.getenv("PAPERLESS_ADMIN_PASSWORD","")
config["PAPERLESS_ADMIN_MAIL"] = os.getenv("PAPERLESS_ADMIN_MAIL","")
config["PAPERLESS_COOKIE_PREFIX"] = os.getenv("PAPERLESS_COOKIE_PREFIX","")
config["PAPERLESS_URL"] = os.getenv("host","")
config["PAPERLESS_ALLOWED_HOSTS"] = os.getenv("PAPERLESS_ALLOWED_HOSTS","")
config["PAPERLESS_CSRF_TRUSTED_ORIGINS"] = os.getenv("PAPERLESS_CSRF_TRUSTED_ORIGINS","")
config["PAPERLESS_CORS_ALLOWED_HOSTS"] = os.getenv("PAPERLESS_CORS_ALLOWED_HOSTS","")
config["PAPERLESS_USE_X_FORWARD_HOST"] = os.getenv("PAPERLESS_USE_X_FORWARD_HOST","")== "True"
config["PAPERLESS_PROXY_SSL_HEADER"] = os.getenv("PAPERLESS_PROXY_SSL_HEADER","HTTP_X_FORWARDED_PROTO","https")

json.dump(config, fp=sys.stdout)
