#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "LOGIN_RATELIMIT_MAX_BURST",
        "LOGIN_RATELIMIT_SECONDS",
        "ADMIN_RATELIMIT_MAX_BURST",
        "ADMIN_RATELIMIT_SECONDS",
        "ADMIN_TOKEN",
        "SENDS_ALLOWED",
        "EMERGENCY_ACCESS_ALLOWED",
        "WEB_VAULT_ENABLED",
        "SIGNUPS_ALLOWED",
        "SIGNUPS_VERIFY",
        "SIGNUPS_VERIFY_RESEND_TIME",
        "SIGNUPS_VERIFY_RESEND_LIMIT",
        "SIGNUPS_DOMAINS_WHITELIST",
        "SMTP_HOST",
        "SMTP_FROM",
        "SMTP_FROM_NAME",
        "SMTP_SECURITY",
        "SMTP_USERNAME",
        "SMTP_PASSWORD",
        "SMTP_AUTH_MECHANISM",
        "SMTP_HOST",
    ]:
    agent.set_env(evar, original_environment[evar])
